name: PHPCS check

on: pull_request

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
          run: composer install --prefer-dist --no-progress
        - name: Check Composer
          run: composer -v
        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
            enable_warnings: true
            phpcs_bin_path: './'